In [62]:
import sys
!{sys.executable} -m pip install pandas

Requirement already satisfied: pandas in c:\users\asus\appdata\local\python\pythoncore-3.14-64\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in c:\users\asus\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\asus\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import requests

In [6]:
from pprint import pprint

In [7]:
import pandas as pd

In [12]:
response = requests.get("http://rest.uniprot.org/uniprotkb/p0dmv8") 
print(type(response))

<class 'requests.models.Response'>

In [13]:
record = response.json()
pprint(record)

{'annotationScore': 5.0,
 'comments': [{'commentType': 'FUNCTION',
               'texts': [{'evidences': [{'evidenceCode': 'ECO:0000250',
                                         'id': 'P0DMW0',
                                         'source': 'UniProtKB'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '22528486',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '23973223',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '24318877',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '24613385',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '27137183',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '27708256',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '28842558',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '9499401',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000303',
                                         'id': '24012426',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000303',
                                         'id': '26865365',
                                         'source': 'PubMed'}],
                          'value': 'Molecular chaperone implicated in a wide '
                                   'variety of cellular processes, including '
                                   'protection of the proteome from stress, '
                                   'folding and transport of newly synthesized '
                                   'polypeptides, activation of proteolysis of '
                                   'misfolded proteins and the formation and '
                                   'dissociation of protein complexes. Plays a '
                                   'pivotal role in the protein quality '
                                   'control system, ensuring the correct '
                                   'folding of proteins, the re-folding of '
                                   'misfolded proteins and controlling the '
                                   'targeting of proteins for subsequent '
                                   'degradation. This is achieved through '
                                   'cycles of ATP binding, ATP hydrolysis and '
                                   'ADP release, mediated by co-chaperones. '
                                   'The co-chaperones have been shown to not '
                                   'only regulate different steps of the '
                                   'ATPase cycle, but they also have an '
                                   'individual specificity such that one '
                                   'co-chaperone may promote folding of a '
                                   'substrate while another may promote '
                                   'degradation. The affinity for polypeptides '
                                   'is regulated by its nucleotide bound '
                                   'state. In the ATP-bound form, it has a low '
                                   'affinity for substrate proteins. However, '
                                   'upon hydrolysis of the ATP to ADP, it '
                                   'undergoes a conformational change that '
                                   'increases its affinity for substrate '
                                   'proteins. It goes through repeated cycles '
                                   'of ATP hydrolysis and nucleotide exchange, '
                                   'which permits cycles of substrate binding '
                                   'and release. The co-chaperones are of '
                                   'three types: J-domain co-chaperones such '
                                   'as HSP40s (stimulate ATPase hydrolysis by '
                                   'HSP70), the nucleotide exchange factors '
                                   '(NEF) such as BAG1/2/3 (facilitate '
                                   'conversion of HSP70 from the ADP-bound to '
                                   'the ATP-bound state thereby promoting '
                                   'substrate release), and the TPR domain '
                                   'chaperones such as HOPX and STUB1 '
                                   '(PubMed:24012426, PubMed:24318877, '
                                   'PubMed:26865365). Maintains protein '
                                   'homeostasis during cellular stress through '
                                   'two opposing mechanisms: protein refolding '
                                   'and degradation. Its '
                                   'acetylation/deacetylation state determines '
                                   'whether it functions in protein refolding '
                                   'or protein degradation by controlling the '
                                   'competitive binding of co-chaperones HOPX '
                                   'and STUB1. During the early stress '
                                   'response, the acetylated form binds to '
                                   'HOPX which assists in chaperone-mediated '
                                   'protein refolding, thereafter, it is '
                                   'deacetylated and binds to ubiquitin ligase '
                                   'STUB1 that promotes ubiquitin-mediated '
                                   'protein degradation (PubMed:27708256). '
                                   'Regulates centrosome integrity during '
                                   'mitosis, and is required for the '
                                   'maintenance of a functional mitotic '
                                   'centrosome that supports the assembly of a '
                                   'bipolar mitotic spindle (PubMed:27137183). '
                                   'Enhances STUB1-mediated SMAD3 '
                                   'ubiquitination and degradation and '
                                   'facilitates STUB1-mediated inhibition of '
                                   'TGF-beta signaling (PubMed:24613385). '
                                   'Essential for STUB1-mediated '
                                   'ubiquitination and degradation of FOXP3 in '
                                   'regulatory T-cells (Treg) during '
                                   'inflammation (PubMed:23973223). Required '
                                   'as a co-chaperone for optimal STUB1/CHIP '
                                   'ubiquitination of NFATC3 (By similarity). '
                                   'Negatively regulates heat shock-induced '
                                   'HSF1 transcriptional activity during the '
                                   'attenuation and recovery phase period of '
                                   'the heat shock response (PubMed:9499401). '
                                   'Involved in the clearance of misfolded '
                                   'PRDM1/Blimp-1 proteins. Sequesters them in '
                                   'the cytoplasm and promotes their '
                                   'association with SYNV1/HRD1, leading to '
                                   'proteasomal degradation '
                                   '(PubMed:28842558)'}]},
              {'commentType': 'FUNCTION',
               'texts': [{'evidences': [{'evidenceCode': 'ECO:0000269',
                                         'id': '16537599',
                                         'source': 'PubMed'}],
                          'value': '(Microbial infection) In case of rotavirus '
                                   'A infection, serves as a post-attachment '
                                   'receptor for the virus to facilitate entry '
                                   'into the cell'}]},
              {'commentType': 'SUBUNIT',
               'texts': [{'evidences': [{'evidenceCode': 'ECO:0000250',
                                         'id': 'P0DMW0',
                                         'source': 'UniProtKB'},
                                        {'evidenceCode': 'ECO:0000250',
                                         'id': 'Q61696',
                                         'source': 'UniProtKB'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '10216320',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '11274138',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '12853476',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '14503850',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '15383005',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '15963462',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '17182002',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '17233114',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '17289661',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '17947705',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '18620420',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '20053985',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '20072699',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '20179333',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '20223214',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '21081504',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '22528486',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '23921388',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '23973223',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '24270810',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '24318877',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '24613385',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '24790089',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '25281747',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '27133716',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '27137183',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '27708256',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '27884606',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '7935376',
                                         'source': 'PubMed'},
                                        {'evidenceCode': 'ECO:0000269',
                                         'id': '9499401',
                                         'source': 'PubMed'}],
                          'value': 'Component of the CatSper complex. '
                                   'Identified in a IGF2BP1-dependent mRNP '
                                   'granule complex containing untranslated '
                                   'mRNAs (PubMed:17289661). Interacts with '
                                   'CHCHD3, DNAJC7, IRAK1BP1, PPP5C and TSC2 '
                                   '(PubMed:12853476, PubMed:15383005, '
                                   'PubMed:15963462, PubMed:17233114, '
                                   'PubMed:18620420, PubMed:21081504). '
                                   'Interacts with TERT; the interaction '
                                   'occurs in the absence of the RNA '
                                   'component, TERC, and dissociates once the '
                                   'TERT complex has formed (PubMed:11274138). '
                                   'Interacts with TRIM5 (via B30.2/SPRY '
                                   'domain) (PubMed:20053985). Interacts with '
                                   'METTL21A (PubMed:23921388). Interacts with '
                                   'DNAAF2 (By similarity). Interacts with '
                                   'PRKN (PubMed:24270810). Interacts with '
                                   'FOXP3 (PubMed:23973223). Interacts with '
                                   'NOD2; the interaction enhances NOD2 '
                                   'stability (PubMed:24790089). Interacts '
                                   'with DNAJC9 (via J domain) '
                                   '(PubMed:17182002). Interacts with ATF5; '
                                   'the interaction protects ATF5 from '
                                   'degradation via proteasome-dependent and '
                                   'caspase-dependent processes '
                                   '(PubMed:22528486). Interacts with RNF207 '
                                   '(via the C-terminus); this interaction '
                                   'additively increases KCNH2 expression '
                                   '(PubMed:25281747). Interacts with HSF1 '
                                   '(via transactivation domain); this '
                                   'interaction results in the inhibition of '
                                   'heat shock- and HSF1-induced '
                                   'transcriptional activity during the '
                                   'attenuation and recovery phase period of '
                                   'the heat shock response (PubMed:7935376, '
                                   'PubMed:9499401). Interacts with NAA10, '
                                   'HSP40, HSP90 and HDAC4. Interacts (via '
                                   'C-terminus) with STUB1 (via TPR repeats) '
                                   '(By similarity). The acetylated form and '
                                   'the non-acetylated form interact with HOPX '
                                   'and STUB1 respectively (PubMed:27708256). '
                                   'Interacts with NEDD1 (PubMed:27137183). '
                                   'Interacts (via NBD) with BAG1, BAG2, BAG3 '
                                   'and HSPH1/HSP105 (PubMed:24318877). '
                                   'Interacts with SMAD3 (PubMed:24613385). '
                                   'Interacts with DNAJC8 (PubMed:27133716). '
                                   'Interacts with NLRP12 (PubMed:17947705). '
                                   'Interacts with PGLYRP (By similarity). '
                                   'Forms a ternary complex with BAG3 and '
                                   'HSPB8 (PubMed:27884606). Interacts with '
                                   'TTC1 and HSP40/DNAJB1; these interactions '
                                   'prevent the negative role of HSPBP1 on '
                                   'HSP70 folding (PubMed:14503850)'}]},
              {'commentType': 'INTERACTION',
               'interactions': [{'interactantOne': {'intActId': 'EBI-11052499',
                                                    'uniProtKBAccession': 'P0DMV8'},
                                 'interactantTwo': {'geneName': 'ATXN1',
                                                    'intActId': 'EBI-930964',
                                                    'uniProtKBAccession': 'P54253'},
                                 'numberOfExperiments': 3,
                                 'organismDiffer': False},
                                {'interactantOne': {'intActId': 'EBI-11052499',
                                                    'uniProtKBAccession': 'P0DMV8'},
                                 'interactantTwo': {'geneName': 'HTT',

In [20]:
params = {
    'fields': ["accession", "gene_names", "id", "length", "protein_name",]
} 

response = requests.get("http://rest.uniprot.org/uniprotkb/p0dmv8", params = params) 
pprint(response.json())

{'entryType': 'UniProtKB reviewed (Swiss-Prot)',
 'extraAttributes': {'uniParcId': 'UPI0000000C40'},
 'genes': [{'geneName': {'value': 'HSPA1A'},
            'synonyms': [{'evidences': [{'evidenceCode': 'ECO:0000303',
                                         'id': '24318877',
                                         'source': 'PubMed'}],
                          'value': 'HSP72'},
                         {'value': 'HSPA1'},
                         {'value': 'HSX70'}]}],
 'primaryAccession': 'P0DMV8',
 'proteinDescription': {'alternativeNames': [{'fullName': {'value': 'Heat '
                                                                    'shock 70 '
                                                                    'kDa '
                                                                    'protein '
                                                                    '1'},
                                              'shortNames': [{'evidences': [{'evidenceCode': 'ECO:0000303',
                                                                             'id': '14656967',
                                                                             'source': 'PubMed'},
                                                                            {'evidenceCode': 'ECO:0000303',
                                                                             'id': '2538825',
                                                                             'source': 'PubMed'}],
                                                              'value': 'HSP70-1'},
                                                             {'value': 'HSP70.1'}]},
                                             {'fullName': {'value': 'Heat '
                                                                    'shock '
                                                                    'protein '
                                                                    'family A '
                                                                    'member '
                                                                    '1A'}}],
                        'recommendedName': {'fullName': {'evidences': [{'evidenceCode': 'ECO:0000312',
                                                                        'id': 'HGNC:5232',
                                                                        'source': 'HGNC'}],
                                                         'value': 'Heat shock '
                                                                  '70 kDa '
                                                                  'protein '
                                                                  '1A'}}},
 'sequence': {'length': 641},
 'uniProtkbId': 'HS71A_HUMAN'}

In [17]:

accession = "P0DMV8"
url = f"https://www.uniprot.org/uniprot/{accession}.fasta"
response = requests.get(url)
print(response.text)

>sp|P0DMV8|HS71A_HUMAN Heat shock 70 kDa protein 1A OS=Homo sapiens OX=9606 GN=HSPA1A PE=1 SV=1
MAKAAAIGIDLGTTYSCVGVFQHGKVEIIANDQGNRTTPSYVAFTDTERLIGDAAKNQVA
LNPQNTVFDAKRLIGRKFGDPVVQSDMKHWPFQVINDGDKPKVQVSYKGETKAFYPEEIS
SMVLTKMKEIAEAYLGYPVTNAVITVPAYFNDSQRQATKDAGVIAGLNVLRIINEPTAAA
IAYGLDRTGKGERNVLIFDLGGGTFDVSILTIDDGIFEVKATAGDTHLGGEDFDNRLVNH
FVEEFKRKHKKDISQNKRAVRRLRTACERAKRTLSSSTQASLEIDSLFEGIDFYTSITRA
RFEELCSDLFRSTLEPVEKALRDAKLDKAQIHDLVLVGGSTRIPKVQKLLQDFFNGRDLN
KSINPDEAVAYGAAVQAAILMGDKSENVQDLLLLDVAPLSLGLETAGGVMTALIKRNSTI
PTKQTQIFTTYSDNQPGVLIQVYEGERAMTKDNNLLGRFELSGIPPAPRGVPQIEVTFDI
DANGILNVTATDKSTGKANKITITNDKGRLSKEEIERMVQEAEKYKAEDEVQRERVSAKN
ALESYAFNMKSAVEDEGLKGKISEADKKKVLDKCQEVISWLDANTLAEKDEFEHKRKELE
QVCNPIISGLYQGAGGPGPGGFGAQGPKGGSGSGPTIEEVD

In [8]:
query = (
    'family:"Heat shock protein 70 family" AND reviewed:true AND '
    '(organism_id:9606 OR organism_id:10090 OR organism_id:3702 OR organism_id:83333)')

In [9]:
params = {
    'query': query,
}
response = requests.get("http://rest.uniprot.org/uniprotkb/search", params = params)

In [10]:
results = response.json()['results']
print(len(results))

25

In [13]:
def print_summary_line(record):
    """ 
    Print a summary line for a UniProt record.
    
    Args:
        record (dict): A UniProt record as a dictionary.

    Returns:
        None
    """

    up_id = record.get('uniProtkbId', 'N/A') 

    try:
        protein_name = record['proteinDescription']['recommendedName']['fullName']['value'] 
    except KeyError: 
        protein_name="N/A" 

    try: 
        gene_name = record['genes'][0]['geneName']['value'] 
    except KeyError: 
        gene_name="N/A" 

    try: 
        length = record['sequence']['length'] 
    except KeyError: 
        length="N/A"
          
    try:
         description = record['proteinDescription']['recommendedName']['fullName']['value']
    except KeyError:
         description = "N/A"

    try:
        organism = record['organism']['scientificName']
    except KeyError:
        organism = "N/A" 

    try:
        function = "N/A"
        for comment in record['comments']:
            if comment.get('commentType') == 'FUNCTION':
                function = comment['texts'][0]['value']
                break
    except (KeyError, IndexError, TypeError):
        function = "N/A"    

    try:
        location = "N/A"
        for comment in record['comments']:
            if comment.get('commentType') == 'SUBCELLULAR LOCATION':
                location = comment['subcellularLocations'][0]['location']['value']
                break
    except (KeyError, IndexError, TypeError):
        location = "N/A"


    try:
        taxon_id = record['organism']['taxonId']
    except KeyError:
        taxon_id = "N/A"

    print(f"{up_id}, {protein_name}, {gene_name}, {length}, {description}, {organism}, {function}, {location}, ({taxon_id})")

In [14]:
for record in results:
    print_summary_line(record)

HSP7E_HUMAN, Heat shock 70 kDa protein 14, HSPA14, 509, Heat shock 70 kDa protein 14, Homo sapiens, Component of the ribosome-associated complex (RAC), a complex involved in folding or maintaining nascent polypeptides in a folding-competent state. In the RAC complex, binds to the nascent polypeptide chain, while DNAJC2 stimulates its ATPase activity, Cytoplasm, cytosol, (9606)
HS71L_HUMAN, Heat shock 70 kDa protein 1-like, HSPA1L, 641, Heat shock 70 kDa protein 1-like, Homo sapiens, Molecular chaperone implicated in a wide variety of cellular processes, including protection of the proteome from stress, folding and transport of newly synthesized polypeptides, activation of proteolysis of misfolded proteins and the formation and dissociation of protein complexes. Plays a pivotal role in the protein quality control system, ensuring the correct folding of proteins, the re-folding of misfolded proteins and controlling the targeting of proteins for subsequent degradation. This is achieved through cycles of ATP binding, ATP hydrolysis and ADP release, mediated by co-chaperones. The affinity for polypeptides is regulated by its nucleotide bound state. In the ATP-bound form, it has a low affinity for substrate proteins. However, upon hydrolysis of the ATP to ADP, it undergoes a conformational change that increases its affinity for substrate proteins. It goes through repeated cycles of ATP hydrolysis and nucleotide exchange, which permits cycles of substrate binding and release (PubMed:26865365). Positive regulator of PRKN translocation to damaged mitochondria (PubMed:24270810), N/A, (9606)
HYOU1_HUMAN, Hypoxia up-regulated protein 1, HYOU1, 999, Hypoxia up-regulated protein 1, Homo sapiens, Has a pivotal role in cytoprotective cellular mechanisms triggered by oxygen deprivation. Promotes HSPA5/BiP-mediated ATP nucleotide exchange and thereby activates the unfolded protein response (UPR) pathway in the presence of endoplasmic reticulum stress (By similarity). May play a role as a molecular chaperone and participate in protein folding, Endoplasmic reticulum lumen, (9606)
BIP_HUMAN, Endoplasmic reticulum chaperone BiP, HSPA5, 654, Endoplasmic reticulum chaperone BiP, Homo sapiens, Endoplasmic reticulum chaperone that plays a key role in protein folding and quality control in the endoplasmic reticulum lumen (PubMed:2294010, PubMed:23769672, PubMed:23990668, PubMed:28332555). Involved in the correct folding of proteins and degradation of misfolded proteins via its interaction with DNAJC10/ERdj5, probably to facilitate the release of DNAJC10/ERdj5 from its substrate (By similarity). Acts as a key repressor of the EIF2AK3/PERK and ERN1/IRE1-mediated unfolded protein response (UPR) (PubMed:11907036, PubMed:1550958, PubMed:19538957, PubMed:36739529). In the unstressed endoplasmic reticulum, recruited by DNAJB9/ERdj4 to the luminal region of ERN1/IRE1, leading to disrupt the dimerization of ERN1/IRE1, thereby inactivating ERN1/IRE1 (By similarity). Also binds and inactivates EIF2AK3/PERK in unstressed cells (PubMed:11907036). Accumulation of misfolded protein in the endoplasmic reticulum causes release of HSPA5/BiP from ERN1/IRE1 and EIF2AK3/PERK, allowing their homodimerization and subsequent activation (PubMed:11907036). Plays an auxiliary role in post-translational transport of small presecretory proteins across endoplasmic reticulum (ER). May function as an allosteric modulator for SEC61 channel-forming translocon complex, likely cooperating with SEC62 to enable the productive insertion of these precursors into SEC61 channel. Appears to specifically regulate translocation of precursors having inhibitory residues in their mature region that weaken channel gating. May also play a role in apoptosis and cell proliferation (PubMed:26045166), Endoplasmic reticulum lumen, (9606)
HSP72_HUMAN, Heat shock-related 70 kDa protein 2, HSPA2, 639, Heat shock-related 70 kDa protein 2, Homo sapiens, Molecular chaperone implicated in a wide variety of cellular processes, including protection of the proteome from stress, folding and transport of newly synthesized polypeptides, activation of proteolysis of misfolded proteins and the formation and dissociation of protein complexes. Plays a pivotal role in the protein quality control system, ensuring the correct folding of proteins, the re-folding of misfolded proteins and controlling the targeting of proteins for subsequent degradation. This is achieved through cycles of ATP binding, ATP hydrolysis and ADP release, mediated by co-chaperones. The affinity for polypeptides is regulated by its nucleotide bound state. In the ATP-bound form, it has a low affinity for substrate proteins. However, upon hydrolysis of the ATP to ADP, it undergoes a conformational change that increases its affinity for substrate proteins. It goes through repeated cycles of ATP hydrolysis and nucleotide exchange, which permits cycles of substrate binding and release (PubMed:26865365). Plays a role in spermatogenesis. In association with SHCBP1L may participate in the maintenance of spindle integrity during meiosis in male germ cells (By similarity), Cytoplasm, cytoskeleton, spindle, (9606)
HS71B_HUMAN, Heat shock 70 kDa protein 1B, HSPA1B, 641, Heat shock 70 kDa protein 1B, Homo sapiens, Molecular chaperone implicated in a wide variety of cellular processes, including protection of the proteome from stress, folding and transport of newly synthesized polypeptides, activation of proteolysis of misfolded proteins and the formation and dissociation of protein complexes. Plays a pivotal role in the protein quality control system, ensuring the correct folding of proteins, the re-folding of misfolded proteins and controlling the targeting of proteins for subsequent degradation. This is achieved through cycles of ATP binding, ATP hydrolysis and ADP release, mediated by co-chaperones. The co-chaperones have been shown to not only regulate different steps of the ATPase cycle, but they also have an individual specificity such that one co-chaperone may promote folding of a substrate while another may promote degradation. The affinity for polypeptides is regulated by its nucleotide bound state. In the ATP-bound form, it has a low affinity for substrate proteins. However, upon hydrolysis of the ATP to ADP, it undergoes a conformational change that increases its affinity for substrate proteins. It goes through repeated cycles of ATP hydrolysis and nucleotide exchange, which permits cycles of substrate binding and release. The co-chaperones are of three types: J-domain co-chaperones such as HSP40s (stimulate ATPase hydrolysis by HSP70), the nucleotide exchange factors (NEF) such as BAG1/2/3 (facilitate conversion of HSP70 from the ADP-bound to the ATP-bound state thereby promoting substrate release), and the TPR domain chaperones such as HOPX and STUB1 (PubMed:24012426, PubMed:24318877, PubMed:26865365). Maintains protein homeostasis during cellular stress through two opposing mechanisms: protein refolding and degradation. Its acetylation/deacetylation state determines whether it functions in protein refolding or protein degradation by controlling the competitive binding of co-chaperones HOPX and STUB1. During the early stress response, the acetylated form binds to HOPX which assists in chaperone-mediated protein refolding, thereafter, it is deacetylated and binds to ubiquitin ligase STUB1 that promotes ubiquitin-mediated protein degradation (PubMed:27708256). Regulates centrosome integrity during mitosis, and is required for the maintenance of a functional mitotic centrosome that supports the assembly of a bipolar mitotic spindle (PubMed:27137183). Enhances STUB1-mediated SMAD3 ubiquitination and degradation and facilitates STUB1-mediated inhibition of TGF-beta signaling (PubMed:24613385). Essential for STUB1-mediated ubiquitination and degradation of FOXP3 in regulatory T-cells (Treg) during inflammation (PubMed:23973223), Cytoplasm, (9606)
HSP7C_HUMAN, Heat shock cognate 71 kDa protein, HSPA8, 646, Heat shock cognate 71 kDa protein, Homo sapiens, Molecular chaperone implicated in a wide variety of cellular processes, including protection of the proteome from stress, folding and transport of newly synthesized polypeptides, chaperone-mediated autophagy, activation of proteolysis of misfolded proteins, formation and dissociation of protein complexes, and antigen presentation. Plays a pivotal role in the protein quality control system, ensuring the correct folding of proteins, the re-folding of misfolded proteins and controlling the targeting of proteins for subsequent degradation (PubMed:21148293, PubMed:21150129, PubMed:23018488, PubMed:24732912, PubMed:27916661, PubMed:2799391, PubMed:36586411). This is achieved through cycles of ATP binding, ATP hydrolysis and ADP release, mediated by co-chaperones (PubMed:12526792, PubMed:21148293, PubMed:21150129, PubMed:23018488, PubMed:24732912, PubMed:27916661). The co-chaperones have been shown to not only regulate different steps of the ATPase cycle of HSP70, but they also have an individual specificity such that one co-chaperone may promote folding of a substrate while another may promote degradation (PubMed:12526792, PubMed:21148293, PubMed:21150129, PubMed:23018488, PubMed:24732912, PubMed:27916661). The affinity of HSP70 for polypeptides is regulated by its nucleotide bound state. In the ATP-bound form, it has a low affinity for substrate proteins. However, upon hydrolysis of the ATP to ADP, it undergoes a conformational change that increases its affinity for substrate proteins. HSP70 goes through repeated cycles of ATP hydrolysis and nucleotide exchange, which permits cycles of substrate binding and release. The HSP70-associated co-chaperones are of three types: J-domain co-chaperones HSP40s (stimulate ATPase hydrolysis by HSP70), the nucleotide exchange factors (NEF) such as BAG1/2/3 (facilitate conversion of HSP70 from the ADP-bound to the ATP-bound state thereby promoting substrate release), and the TPR domain chaperones such as HOPX and STUB1 (PubMed:24121476, PubMed:24318877, PubMed:26865365, PubMed:27474739). Plays a critical role in mitochondrial import, delivers preproteins to the mitochondrial import receptor TOMM70 (PubMed:12526792). Acts as a repressor of transcriptional activation. Inhibits the transcriptional coactivator activity of CITED1 on Smad-mediated transcription. Component of the PRP19-CDC5L complex that forms an integral part of the spliceosome and is required for activating pre-mRNA splicing. May have a scaffolding role in the spliceosome assembly as it contacts all other components of the core complex. Binds bacterial lipopolysaccharide (LPS) and mediates LPS-induced inflammatory response, including TNF secretion by monocytes (PubMed:10722728, PubMed:11276205). Substrate recognition component in chaperone-mediated autophagy (CMA), a selective protein degradation process that mediates degradation of proteins with a -KFERQ motif: HSPA8/HSC70 specifically recognizes and binds cytosolic proteins bearing a -KFERQ motif and promotes their recruitment to the surface of the lysosome where they bind to lysosomal protein LAMP2 (PubMed:11559757, PubMed:2799391, PubMed:36586411). KFERQ motif-containing proteins are eventually transported into the lysosomal lumen where they are degraded (PubMed:11559757, PubMed:2799391, PubMed:36586411). In conjunction with LAMP2, facilitates MHC class II presentation of cytoplasmic antigens by guiding antigens to the lysosomal membrane for interaction with LAMP2 which then elicits MHC class II presentation of peptides to the cell membrane (PubMed:15894275). Participates in the ER-associated degradation (ERAD) quality control pathway in conjunction with J domain-containing co-chaperones and the E3 ligase STUB1 (PubMed:23990462). It is recruited to clathrin-coated vesicles through its interaction with DNAJC6 leading to activation of HSPA8/HSC70 ATPase activity and therefore uncoating of clathrin-coated vesicles (By similarity), Cytoplasm, (9606)
HSP76_HUMAN, Heat shock 70 kDa protein 6, HSPA6, 643, Heat shock 70 kDa protein 6, Homo sapiens, Molecular chaperone implicated in a wide variety of cellular processes, including protection of the proteome from stress, folding and transport of newly synthesized polypeptides, activation of proteolysis of misfolded proteins and the formation and dissociation of protein complexes. Plays a pivotal role in the protein quality control system, ensuring the correct folding of proteins, the re-folding of misfolded proteins and controlling the targeting of proteins for subsequent degradation. This is achieved through cycles of ATP binding, ATP hydrolysis and ADP release, mediated by co-chaperones. The affinity for polypeptides is regulated by its nucleotide bound state. In the ATP-bound form, it has a low affinity for substrate proteins. However, upon hydrolysis of the ATP to ADP, it undergoes a conformational change that increases its affinity for substrate proteins. It goes through repeated cycles of ATP hydrolysis and nucleotide exchange, which permits cycles of substrate binding and release (PubMed:26865365), N/A, (9606)
HSPA9_HUMAN, Stress-70 protein, mitochondrial, HSPA9, 679, Stress-70 protein, mitochondrial, Homo sapiens, Mitochondrial chaperone that plays a key role in mitochondrial protein import, folding, and assembly. Plays an essential role in the protein quality control system, the correct folding of proteins, the re-folding of misfolded proteins, and the targeting of proteins for subsequent degradation. These processes are achieved through cycles of ATP binding, ATP hydrolysis, and ADP release, mediated by co-chaperones (PubMed:18632665, PubMed:25615450, PubMed:28848044, PubMed:30933555, PubMed:31177526). In mitochondria, it associates with the TIM (translocase of the inner membrane) protein complex to assist in the import and folding of mitochondrial proteins (By similarity). Plays an important role in mitochondrial iron-sulfur cluster (ISC) biogenesis, interacts with and stabilizes ISC cluster assembly proteins FXN, NFU1, NFS1 and ISCU (PubMed:26702583). Regulates erythropoiesis via stabilization of ISC assembly (PubMed:21123823, PubMed:26702583). Regulates mitochondrial calcium-dependent apoptosis by coupling two calcium channels, ITPR1 and VDAC1, at the mitochondria-associated endoplasmic reticulum (ER) membrane to facilitate calcium transport from the ER lumen to the mitochondria intermembrane space, providing calcium for the downstream calcium channel MCU, which releases it into the mitochondrial matrix (By similarity). Although primarily located in the mitochondria, it is also found in other cellular compartments. In the cytosol, it associates with proteins involved in signaling, apoptosis, or senescence. It may play a role in cell cycle regulation via its interaction with and promotion of degradation of TP53 (PubMed:24625977, PubMed:26634371). May play a role in the control of cell proliferation and cellular aging (By similarity). Protects against reactive oxygen species (ROS) (By similarity). Extracellular HSPA9 plays a cytoprotective role by preventing cell lysis following immune attack by the membrane attack complex by disrupting formation of the complex (PubMed:16091382), Mitochondrion, (9606)
HSP13_HUMAN, Heat shock 70 kDa protein 13, HSPA13, 471, Heat shock 70 kDa protein 13, Homo sapiens, Has peptide-independent ATPase activity, Microsome, (9606)
HS71A_HUMAN, Heat shock 70 kDa protein 1A, HSPA1A, 641, Heat shock 70 kDa protein 1A, Homo sapiens, Molecular chaperone implicated in a wide variety of cellular processes, including protection of the proteome from stress, folding and transport of newly synthesized polypeptides, activation of proteolysis of misfolded proteins and the formation and dissociation of protein complexes. Plays a pivotal role in the protein quality control system, ensuring the correct folding of proteins, the re-folding of misfolded proteins and controlling the targeting of proteins for subsequent degradation. This is achieved through cycles of ATP binding, ATP hydrolysis and ADP release, mediated by co-chaperones. The co-chaperones have been shown to not only regulate different steps of the ATPase cycle, but they also have an individual specificity such that one co-chaperone may promote folding of a substrate while another may promote degradation. The affinity for polypeptides is regulated by its nucleotide bound state. In the ATP-bound form, it has a low affinity for substrate proteins. However, upon hydrolysis of the ATP to ADP, it undergoes a conformational change that increases its affinity for substrate proteins. It goes through repeated cycles of ATP hydrolysis and nucleotide exchange, which permits cycles of substrate binding and release. The co-chaperones are of three types: J-domain co-chaperones such as HSP40s (stimulate ATPase hydrolysis by HSP70), the nucleotide exchange factors (NEF) such as BAG1/2/3 (facilitate conversion of HSP70 from the ADP-bound to the ATP-bound state thereby promoting substrate release), and the TPR domain chaperones such as HOPX and STUB1 (PubMed:24012426, PubMed:24318877, PubMed:26865365). Maintains protein homeostasis during cellular stress through two opposing mechanisms: protein refolding and degradation. Its acetylation/deacetylation state determines whether it functions in protein refolding or protein degradation by controlling the competitive binding of co-chaperones HOPX and STUB1. During the early stress response, the acetylated form binds to HOPX which assists in chaperone-mediated protein refolding, thereafter, it is deacetylated and binds to ubiquitin ligase STUB1 that promotes ubiquitin-mediated protein degradation (PubMed:27708256). Regulates centrosome integrity during mitosis, and is required for the maintenance of a functional mitotic centrosome that supports the assembly of a bipolar mitotic spindle (PubMed:27137183). Enhances STUB1-mediated SMAD3 ubiquitination and degradation and facilitates STUB1-mediated inhibition of TGF-beta signaling (PubMed:24613385). Essential for STUB1-mediated ubiquitination and degradation of FOXP3 in regulatory T-cells (Treg) during inflammation (PubMed:23973223). Required as a co-chaperone for optimal STUB1/CHIP ubiquitination of NFATC3 (By similarity). Negatively regulates heat shock-induced HSF1 transcriptional activity during the attenuation and recovery phase period of the heat shock response (PubMed:9499401). Involved in the clearance of misfolded PRDM1/Blimp-1 proteins. Sequesters them in the cytoplasm and promotes their association with SYNV1/HRD1, leading to proteasomal degradation (PubMed:28842558), Cytoplasm, (9606)
HSP74_HUMAN, Heat shock 70 kDa protein 4, HSPA4, 840, Heat shock 70 kDa protein 4, Homo sapiens, N/A, Cytoplasm, (9606)
HS105_HUMAN, Heat shock protein 105 kDa, HSPH1, 858, Heat shock protein 105 kDa, Homo sapiens, Acts as a nucleotide-exchange factor (NEF) for chaperone proteins HSPA1A and HSPA1B, promoting the release of ADP from HSPA1A/B thereby triggering client/substrate protein release (PubMed:24318877). Prevents the aggregation of denatured proteins in cells under severe stress, on which the ATP levels decrease markedly. Inhibits HSPA8/HSC70 ATPase and chaperone activities (By similarity), Cytoplasm, (9606)
DNAK_ECOLI, Chaperone protein DnaK, dnaK, 638, Chaperone protein DnaK, Escherichia coli (strain K12), Plays an essential role in the initiation of phage lambda DNA replication, where it acts in an ATP-dependent fashion with the DnaJ protein to release lambda O and P proteins from the preprimosomal complex. DnaK is also involved in chromosomal DNA replication, possibly through an analogous interaction with the DnaA protein. Also participates actively in the response to hyperosmotic shock, Cytoplasm, (83333)

In [15]:
def get_record_dict(record):
    """ 
    Extract relevant fields from a UniProt record and return them as a dictionary.
    
    Args:
        record (dict): A UniProt record as a dictionary.

    Returns:
        dict: A dictionary containing the extracted fields.
    """

    # extract relevant fields from the record, substituting "N/A" if a field is missing
    up_id = record.get('primaryAccession', 'N/A')
    entry_name = record.get('uniProtkbId', 'N/A')

    try:
        protein_name = record['proteinDescription']['recommendedName']['fullName']['value'] 
    except KeyError: 
        protein_name="N/A" 

    try: 
        gene_name = record['genes'][0]['geneName']['value'] 
    except KeyError: 
        gene_name="N/A"   

    try: 
        length = record['sequence']['length'] 
    except KeyError: 
        length="N/A"  

    try:
         description = record['proteinDescription']['recommendedName']['fullName']['value']
    except KeyError:
         description = "N/A"

    try:
        organism = record['organism']['scientificName']
    except KeyError:
        organism = "N/A" 

    try:
        function = "N/A"
        for comment in record['comments']:
            if comment.get('commentType') == 'FUNCTION':
                function = comment['texts'][0]['value']
                break
    except (KeyError, IndexError, TypeError):
        function = "N/A" 

    try:
        location = "N/A"
        for comment in record['comments']:
            if comment.get('commentType') == 'SUBCELLULAR LOCATION':
                location = comment['subcellularLocations'][0]['location']['value']
                break
    except (KeyError, IndexError, TypeError):
        location = "N/A"


    try:
        taxon_id = record['organism']['taxonId']
    except KeyError:
        taxon_id = "N/A"

    return {
        'UniProtID': up_id, 
        'EntryName': entry_name,
        'ProteinName': description,
        'GeneName': gene_name,
        'Length': length,
        'Organism': organism, 
        'Function': function,
        'CellularLocation': location,
        'TaxonID': taxon_id 
        
    }


res_summary = []
for record in results:
    res_summary.append(get_record_dict(record))
    # limit to 25 records for display purposes (and speed!)
    if len(res_summary)>= 25:
        break

summary_df = pd.DataFrame(res_summary)

summary_df

,UniProtID,EntryName,ProteinName,GeneName,Length,Organism,Function,CellularLocation,TaxonID
0,Q0VDF9,HSP7E_HUMAN,Heat shock 70 kDa protein 14,HSPA14,509,Homo sapiens,Component of the ribosome-associated complex (...,"Cytoplasm, cytosol",9606
1,P34931,HS71L_HUMAN,Heat shock 70 kDa protein 1-like,HSPA1L,641,Homo sapiens,Molecular chaperone implicated in a wide varie...,N/A,9606
2,Q9Y4L1,HYOU1_HUMAN,Hypoxia up-regulated protein 1,HYOU1,999,Homo sapiens,Has a pivotal role in cytoprotective cellular ...,Endoplasmic reticulum lumen,9606
3,P11021,BIP_HUMAN,Endoplasmic reticulum chaperone BiP,HSPA5,654,Homo sapiens,Endoplasmic reticulum chaperone that plays a k...,Endoplasmic reticulum lumen,9606
4,P54652,HSP72_HUMAN,Heat shock-related 70 kDa protein 2,HSPA2,639,Homo sapiens,Molecular chaperone implicated in a wide varie...,"Cytoplasm, cytoskeleton, spindle",9606
5,P0DMV9,HS71B_HUMAN,Heat shock 70 kDa protein 1B,HSPA1B,641,Homo sapiens,Molecular chaperone implicated in a wide varie...,Cytoplasm,9606
6,P11142,HSP7C_HUMAN,Heat shock cognate 71 kDa protein,HSPA8,646,Homo sapiens,Molecular chaperone implicated in a wide varie...,Cytoplasm,9606
7,P17066,HSP76_HUMAN,Heat shock 70 kDa protein 6,HSPA6,643,Homo sapiens,Molecular chaperone implicated in a wide varie...,N/A,9606
8,P38646,HSPA9_HUMAN,"Stress-70 protein, mitochondrial",HSPA9,679,Homo sapiens,Mitochondrial chaperone that plays a key role ...,Mitochondrion,9606
9,P48723,HSP13_HUMAN,Heat shock 70 kDa protein 13,HSPA13,471,Homo sapiens,Has peptide-independent ATPase activity,Microsome,9606
10,P0DMV8,HS71A_HUMAN,Heat shock 70 kDa protein 1A,HSPA1A,641,Homo sapiens,Molecular chaperone implicated in a wide varie...,Cytoplasm,9606
11,P34932,HSP74_HUMAN,Heat shock 70 kDa protein 4,HSPA4,840,Homo sapiens,N/A,Cytoplasm,9606
12,Q92598,HS105_HUMAN,Heat shock protein 105 kDa,HSPH1,858,Homo sapiens,Acts as a nucleotide-exchange factor (NEF) for...,Cytoplasm,9606
13,P0A6Y8,DNAK_ECOLI,Chaperone protein DnaK,dnaK,638,Escherichia coli (strain K12),Plays an essential role in the initiation of p...,Cytoplasm,83333
14,P16627,HS71L_MOUSE,Heat shock 70 kDa protein 1-like,Hspa1l,641,Mus musculus,Molecular chaperone implicated in a wide varie...,N/A,10090
15,P17156,HSP72_MOUSE,Heat shock-related 70 kDa protein 2,Hspa2,633,Mus musculus,Molecular chaperone implicated in a wide varie...,"Cytoplasm, cytoskeleton, spindle",10090
16,Q61699,HS105_MOUSE,Heat shock protein 105 kDa,Hsph1,858,Mus musculus,Acts as a nucleotide-exchange factor (NEF) for...,Cytoplasm,10090
17,P20029,BIP_MOUSE,Endoplasmic reticulum chaperone BiP,Hspa5,655,Mus musculus,Endoplasmic reticulum chaperone that plays a k...,Endoplasmic reticulum lumen,10090
18,P38647,HSPA9_MOUSE,"Stress-70 protein, mitochondrial",Hspa9,679,Mus musculus,Mitochondrial chaperone that plays a key role ...,Mitochondrion,10090
19,P63017,HSP7C_MOUSE,Heat shock cognate 71 kDa protein,Hspa8,646,Mus musculus,Molecular chaperone implicated in a wide varie...,Cytoplasm,10090
20,P77319,HSCC_ECOLI,Chaperone protein HscC,hscC,556,Escherichia coli (strain K12),Chaperone that exhibits ATPase activity (PubMe...,Cytoplasm,83333
21,P17879,HS71B_MOUSE,Heat shock 70 kDa protein 1B,Hspa1b,642,Mus musculus,Molecular chaperone implicated in a wide varie...,Cytoplasm,10090
22,Q61696,HS71A_MOUSE,Heat shock 70 kDa protein 1A,Hspa1a,641,Mus musculus,Molecular chaperone implicated in a wide varie...,Cytoplasm,10090
23,Q9JKR6,HYOU1_MOUSE,Hypoxia up-regulated protein 1,Hyou1,999,Mus musculus,Has a pivotal role in cytoprotective cellular ...,Endoplasmic reticulum lumen,10090
24,O95757,HS74L_HUMAN,Heat shock 70 kDa protein 4L,HSPA4L,839,Homo sapiens,Possesses chaperone activity in vitro where it...,Cytoplasm,9606

In [16]:
url = "https://rest.uniprot.org/uniprotkb/search"

In [17]:
params = { 
    "query": "accession:p11021 OR accession:p0A6Y8 OR accession:p38647", 
    "format": "fasta"
} 
response = requests.get(url, params=params)

In [18]:
with open("HSP70.fasta", "w") as fh:
    fh.writelines(response.text)

In [21]:
%pip install rcsb-api

Collecting rcsb-api
  Downloading rcsb_api-1.7.1-py3-none-any.whl.metadata (11 kB)
Collecting graphql-core (from rcsb-api)
  Downloading graphql_core-3.2.8-py3-none-any.whl.metadata (11 kB)
Collecting httpx>=0.26.0 (from rcsb-api)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: nest-asyncio>=1.6.0 in c:\users\asus\appdata\roaming\python\python314\site-packages (from rcsb-api) (1.6.0)
Collecting rustworkx (from rcsb-api)
  Downloading rustworkx-0.17.1-cp39-abi3-win_amd64.whl.metadata (10 kB)
Collecting tqdm (from rcsb-api)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting anyio (from httpx>=0.26.0->rcsb-api)
  Downloading anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: certifi in c:\users\asus\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from httpx>=0.26.0->rcsb-api) (2026.2.25)
Collecting httpcore==1.* (from httpx>=0.26.0->rcsb-api)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in c:\users\asus\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from httpx>=0.26.0->rcsb-api) (3.11)
Collecting h11>=0.16 (from httpcore==1.*->httpx>=0.26.0->rcsb-api)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: numpy<3,>=1.16.0 in c:\users\asus\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from rustworkx->rcsb-api) (2.4.4)
Requirement already satisfied: colorama in c:\users\asus\appdata\roaming\python\python314\site-packages (from tqdm->rcsb-api) (0.4.6)
Downloading rcsb_api-1.7.1-py3-none-any.whl (71 kB)
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Downloading anyio-4.13.0-py3-none-any.whl (114 kB)
Downloading graphql_core-3.2.8-py3-none-any.whl (207 kB)
Downloading rustworkx-0.17.1-cp39-abi3-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 19.7 MB/s  0:00:00
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, rustworkx, h11, graphql-core, anyio, httpcore, httpx, rcsb-api

   ---------------------------------------- 0/8 [tqdm]
   ---------------------------------------- 0/8 [tqdm]
   ---------------------------------------- 0/8 [tqdm]
   ---------------------------------------- 0/8 [tqdm]
   ---------------------------------------- 0/8 [tqdm]
   ----- ---------------------------------- 1/8 [rustworkx]
   ---------- ----------------------------- 2/8 [h11]
   ---------- ----------------------------- 2/8 [h11]
   ---------- ----------------------------- 2/8 [h11]
   --------------- ------------------------ 3/8 [graphql-core]
   --------------- ------------------------ 3/8 [graphql-core]
   --------------- ------------------------ 3/8 [graphql-core]
   --------------- ------------------------ 3/8 [graphql-core]
   --------------- ------------------------ 3/8 [graphql-core]
   --------------- ------------------------ 3/8 [graphql-core]
   --------------- ------------------------ 3/8 [graphql-core]
   --------------- ------------------------ 3/8 [graphql-core]
   --------------- ------------------------ 3/8 [graphql-core]
   --------------- ------------------------ 3/8 [graphql-core]
   --------------- ------------------------ 3/8 [graphql-core]
   --------------- ------------------------ 3/8 [graphql-core]
   --------------- ------------------------ 3/8 [graphql-core]
   --------------- ------------------------ 3/8 [graphql-core]
   --------------- ------------------------ 3/8 [graphql-core]
   --------------- ------------------------ 3/8 [graphql-core]
   --------------- ------------------------ 3/8 [graphql-core]
   --------------- ------------------------ 3/8 [graphql-core]
   -------------------- ------------------- 4/8 [anyio]
   -------------------- ------------------- 4/8 [anyio]
   -------------------- ------------------- 4/8 [anyio]
   -------------------- ------------------- 4/8 [anyio]
   -------------------- ------------------- 4/8 [anyio]
   -------------------- ------------------- 4/8 [anyio]
   ------------------------- -------------- 5/8 [httpcore]
   ------------------------- -------------- 5/8 [httpcore]
   ------------------------- -------------- 5/8 [httpcore]
   ------------------------- -------------- 5/8 [httpcore]
   ------------------------- -------------- 5/8 [httpcore]
   ------------------------------ --------- 6/8 [httpx]
   ------------------------------ --------- 6/8 [httpx]
   ------------------------------ --------- 6/8 [httpx]
   ------------------------------ --------- 6/8 [httpx]
   ----------------------------------- ---- 7/8 [rcsb-api]
   ----------------------------------- ---- 7/8 [rcsb-api]
   ----------------------------------- ---- 7/8 [rcsb-api]
   ---------------------------------------- 8/8 [rcsb-api]

Successfully installed anyio-4.13.0 graphql-core-3.2.8 h11-0.16.0 httpcore-1.0.9 httpx-0.28.1 rcsb-api-1.7.1 rustworkx-0.17.1 tqdm-4.67.3
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script tqdm.exe is installed in 'c:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script httpx.exe is installed in 'c:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
from rcsbapi.search import StructSimilarityQuery

reference_id = "4B9Q"   

q_struct = StructSimilarityQuery(
    structure_search_type="entry_id",
    entry_id=reference_id,
    chain_id="A",
    similarity_type="global",
    target_search_space="polymer_entity_instance"
)
list(q_struct())

['4B9Q',
 '7KO2',
 '5NRO',
 '4JNE',
 '7KRT',
 '4JN4',
 '5E84',
 '7N1R',
 '6ASY',
 '2KHO',
 '7KZI',
 '7SQC',
 '7N6G',
 '5TKY',
 '9BLS',
 '9BLT',
 '7KRW',
 '3D2E',
 '3D2F',
 '2QXL',
 '3C7N',
 '1YUW',
 '7KRV',
 '7KRU',
 '4J8F',
 '7KZU',
 '7PLK']

In [30]:
similar_ids = []
for result in q_struct():
    # results come back as "PDBID.chain" e.g. "4B9Q.A" — extract just the PDB ID
    pdb_id = result.split(".")[0]
    if pdb_id not in similar_ids and pdb_id != reference_id:
        similar_ids.append(pdb_id)
    if len(similar_ids) >= 25:
        break

In [31]:
print(f"Found {len(similar_ids)} structurally similar HSP70 entries")
print(similar_ids)

Found 25 structurally similar HSP70 entries
['7KO2', '5NRO', '4JNE', '7KRT', '4JN4', '5E84', '7N1R', '6ASY', '2KHO', '7KZI', '7SQC', '7N6G', '5TKY', '9BLS', '9BLT', '7KRW', '3D2E', '3D2F', '2QXL', '3C7N', '1YUW', '7KRV', '7KRU', '4J8F', '7KZU']

In [38]:
def get_pdb_record_dict(pdb_id):
    """
    Fetch and extract structural data from a PDB entry via the RCSB Data API.
    Hits three endpoints: entry, polymer_entity, and polymer_entity_instance.

    Args:
        pdb_id (str): A PDB entry ID (e.g. '4B9Q').

    Returns:
        dict: A dictionary containing the extracted structural fields.
    """

    base = "https://data.rcsb.org/rest/v1/core"

    # ── Endpoint 1: Entry-level metadata ──────────────────────────────────
    entry_resp = requests.get(f"{base}/entry/{pdb_id}")
    entry = entry_resp.json() if entry_resp.status_code == 200 else {}

    try:
        title = entry['struct']['title']
    except KeyError:
        title = "N/A"

    try:
        exp_method = entry['exptl'][0]['method']
    except (KeyError, IndexError):
        exp_method = "N/A"

    try:
        resolution = entry['rcsb_entry_info']['resolution_combined'][0]
    except (KeyError, IndexError):
        resolution = "N/A"

    try:
        deposition_date = entry['rcsb_accession_info']['deposit_date']
    except KeyError:
        deposition_date = "N/A"

    # ── Endpoint 2: Polymer entity (chain 1) ──────────────────────────────
    entity_resp = requests.get(f"{base}/polymer_entity/{pdb_id}/1")
    entity = entity_resp.json() if entity_resp.status_code == 200 else {}

    try:
        organism = entity['rcsb_entity_source_organism'][0]['scientific_name']
    except (KeyError, IndexError):
        organism = "N/A"

    try:
        taxonomy_id = entity['rcsb_entity_source_organism'][0]['ncbi_taxonomy_id']
    except (KeyError, IndexError):
        taxonomy_id = "N/A"

    try:
        seq_length = entity['entity_poly']['rcsb_sample_sequence_length']
    except KeyError:
        seq_length = "N/A"

    try:
        sequence = entity['entity_poly']['pdbx_seq_one_letter_code_can']
    except KeyError:
        sequence = "N/A"

    # ── Endpoint 3: Polymer entity instance (chain A) ─────────────────────
    instance_resp = requests.get(f"{base}/polymer_entity_instance/{pdb_id}/A")
    instance = instance_resp.json() if instance_resp.status_code == 200 else {}

    return {
        'PDB_ID':          pdb_id,
        'Title':           title,
        'Organism':        organism,
        'Taxonomy_ID':     taxonomy_id,
        'Exp_Method':      exp_method,
        'Resolution_A':    resolution,
        'Seq_Length':      seq_length,
        'Sequence':        sequence,
    }

In [39]:
pdb_summary = []
for pdb_id in similar_ids:
    pdb_summary.append(get_pdb_record_dict(pdb_id))
    print(f"Fetched: {pdb_id}")  # progress tracker

pdb_df = pd.DataFrame(pdb_summary)
pdb_df

Fetched: 7KO2
Fetched: 5NRO
Fetched: 4JNE
Fetched: 7KRT
Fetched: 4JN4
Fetched: 5E84
Fetched: 7N1R
Fetched: 6ASY
Fetched: 2KHO
Fetched: 7KZI
Fetched: 7SQC
Fetched: 7N6G
Fetched: 5TKY
Fetched: 9BLS
Fetched: 9BLT
Fetched: 7KRW
Fetched: 3D2E
Fetched: 3D2F
Fetched: 2QXL
Fetched: 3C7N
Fetched: 1YUW
Fetched: 7KRV
Fetched: 7KRU
Fetched: 4J8F
Fetched: 7KZU

,PDB_ID,Title,Organism,Taxonomy_ID,Exp_Method,Resolution_A,Seq_Length,Sequence
0,7KO2,Restraining state of near full-length Hsp70 DnaK,Escherichia coli (strain K12),83333,X-RAY DIFFRACTION,2.64,609,MGKIIGIDLGTTNSCVAIMDGTTPRVLENAEGDRTTPSIIAYTQDG...
1,5NRO,Structure of full-length DnaK with bound J-domain,Escherichia coli,562,X-RAY DIFFRACTION,3.25,611,MGKIIGIDLGTTNSCVAIMDGTTPRVLENAEGDRTTPSIIAYTQDG...
2,4JNE,Allosteric opening of the polypeptide-binding ...,Escherichia coli,83333,X-RAY DIFFRACTION,1.96,608,SGKIIGIDLGTTNSCVAIMDGTTPRVLENAEGDRTTPSIIAYTQDG...
3,7KRT,Restraining state of a truncated Hsp70 DnaK,Escherichia coli (strain K12),83333,X-RAY DIFFRACTION,2.79,600,MGKIIGIDLGTTNSCVAIMDGTTPRVLENAEGDRTTPSIIAYTQDG...
4,4JN4,Allosteric opening of the polypeptide-binding ...,Escherichia coli,83333,X-RAY DIFFRACTION,2.3,608,SGKIIGIDLGTTNSCVAIMDGTTPRVLENAEGDRTTPSIIAYTQDG...
5,5E84,ATP-bound state of BiP,Homo sapiens,9606,X-RAY DIFFRACTION,2.99,606,SEDVGTVVGIDLGTTYSCVGVFKNGRVEIIANDQGNRITPSYVAFT...
6,7N1R,A novel and unique ATP hydrolysis to AMP by a ...,Homo sapiens,9606,X-RAY DIFFRACTION,2.03,606,SEDVGTVVGIDLGTTYSCVGVFKNGRVEIIANDQGNRITPSYVAFT...
7,6ASY,BiP-ATP2,Homo sapiens,9606,X-RAY DIFFRACTION,1.85,606,SEDVGTVVGIDLGTTYSCVGVFKNGRVEIIANDQGNRITPSYVAFT...
8,2KHO,NMR-RDC / XRAY structure of E. coli HSP70 (DNA...,Escherichia coli,83333,SOLUTION NMR,N/A,605,MGKIIGIDLGTTNSCVAIMDGTTPRVLENAEGDRTTPSIIAYTQDG...
9,7KZI,Intermediate state (QQQ) of near full-length D...,Escherichia coli (strain K12),83333,X-RAY DIFFRACTION,2.82,628,MGKIIGIDLGTTNSCVAIMDGTTPRVLENAEGDRTTPSIIAYTQDG...
10,7SQC,Ciliary C1 central pair apparatus isolated fro...,Chlamydomonas reinhardtii,3055,ELECTRON MICROSCOPY,3.8,93,MSESQKETFRKYLEQAGAIDVLVKVLVQLYEEPSKPKTALDYIKQC...
11,7N6G,C1 of central pair,Chlamydomonas reinhardtii,3055,ELECTRON MICROSCOPY,3.6,512,MATRAVLQTFERYQKERVAFVTAVAEMAKNPQNIEALQQAGAMALL...
12,5TKY,Crystal structure of the co-translational Hsp7...,Chaetomium thermophilum (strain DSM 1495 / CBS...,759272,X-RAY DIFFRACTION,2.6,621,MGHHHHHHAEEVYDGAIGIDLGTTYSCVAVYEGTNVEIIANEQGNF...
13,9BLS,Structure of the human mitochondrial Hsp70 (mo...,Homo sapiens,9606,ELECTRON MICROSCOPY,2.96,594,MASEAIKGAVVGIDLGTTNSCVAVMEGKQAKVLENAEGARTTPSVV...
14,9BLT,Structure of the human mitochondrial Hsp70 (mo...,Homo sapiens,9606,ELECTRON MICROSCOPY,3.38,594,MASEAIKGAVVGIDLGTTNSCVAVMEGKQAKVLENAEGARTTPSVV...
15,7KRW,Stimulating state of near full-length Hsp70 Dn...,Escherichia coli (strain K12),83333,X-RAY DIFFRACTION,7.7,622,MGKIIGIDLGTTNSCVAIMDGTTPRVLENAEGDRTTPSIIAYTQDG...
16,3D2E,Crystal structure of a complex of Sse1p and Hs...,Saccharomyces cerevisiae,4932,X-RAY DIFFRACTION,2.35,675,MSTPFGLDLGNNNSVLAVARNRGIDIVVNEVSNRSTPSVVGFGPKN...
17,3D2F,Crystal structure of a complex of Sse1p and Hsp70,Saccharomyces cerevisiae,4932,X-RAY DIFFRACTION,2.3,675,MSTPFGLDLGNNNSVLAVARNRGIDIVVNEVSNRSTPSVVGFGPKN...
18,2QXL,"Crystal Structure Analysis of Sse1, a yeast Hs...",Saccharomyces cerevisiae,4932,X-RAY DIFFRACTION,2.41,658,STPFGLDLGNNNSVLAVARNRGIDIVVNEVSNRSTPSVVGFGPKNR...
19,3C7N,Structure of the Hsp110:Hsc70 Nucleotide Excha...,Saccharomyces cerevisiae,4932,X-RAY DIFFRACTION,3.115,668,GPMSTPFGLDLGNNNSVLAVARNRGIDIVVNEVSNRSTPSVVGFGP...
20,1YUW,crystal structure of bovine hsc70(aa1-554)E213...,Bos taurus,9913,X-RAY DIFFRACTION,2.6,554,MSKGPAVGIDLGTTYSCVGVFQHGKVEIIANDQGNRTTPSYVAFTD...
21,7KRV,Stimulating state of disulfide-bridged Hsp70 DnaK,Escherichia coli (strain K12),83333,X-RAY DIFFRACTION,1.92,552,MGKIIGIDLGTTNSCVAIMDGTTPRVLENAEGDRTTPSIIAYTQDG...
22,7KRU,Stimulating state of a truncated Hsp70 DnaK fu...,Escherichia coli (strain K12),83333,X-RAY DIFFRACTION,1.82,552,MGKIIGIDLGTTNSCVAIMDGTTPRVLENAEGDRTTPSIIAYTQDG...
23,4J8F,Crystal structure of a fusion protein containi...,Homo sapiens,9606,X-RAY DIFFRACTION,2.7,561,GAMDPEFMAKAAAIGIDLGTTYSCVGVFQHGKVEIIANDQGNRTTP...
24,7KZU,Quasi-intermediate state (Q) of a truncated Hs...,Escherichia coli (strain K12),83333,X-RAY DIFFRACTION,2.15,552,SGKIIGIDLGTTNSCVAIMDGTTPRVLENAEGDRTTPSIIAYTQDG...